# Generated by Django 3.1 on 2020-09-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mybook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='summary',
            field=models.CharField(default=0, max_length=800),
            preserve_default=False,
        ),
    ]
