# Generated by Django 3.1 on 2020-09-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mybook', '0003_auto_20200927_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
