# Generated by Django 3.1 on 2020-10-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mybook', '0006_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerbook',
            name='reg_status',
            field=models.IntegerField(default=1),
        ),
    ]
