# Generated by Django 3.1 on 2020-10-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mybook', '0007_registerbook_reg_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
