# Generated by Django 3.1 on 2020-10-15 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mybook', '0008_books_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='image_url',
        ),
    ]
