# Generated by Django 3.1 on 2020-10-15 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mybook', '0009_remove_books_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='image2',
        ),
    ]
