# Generated by Django 3.1 on 2020-10-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mybook', '0010_remove_books_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
